class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'files_mirror'
        self.UnzipMirrorCommand = 'ex'
        self.TarMirrorCommand = 'tarmm'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'find'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone@CloneGDriveBot'
        self.CountCommand = 'counts'
        self.WatchCommand = 'youtubemirror5'
        self.TarWatchCommand = 'playlistmirror5'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'

BotCommands = _BotCommands()
